baseURL = "https://blog.1024ai.cc/"
title = "Andy's Analysis"
theme = "reimu"
defaultContentLanguage = "zh"

[author]
name = "Andy"

[languages]
[languages.zh]
languageName = "中文"
languageCode = "zh-CN"
weight = 1
title = "Andy's Analysis"
description = "AI与全球地缘政治跨学科分析"

[languages.en]
languageName = "English"
languageCode = "en"
weight = 2
title = "Andy's Analysis"
description = "Interdisciplinary analysis of Artificial Intelligence and Global Geopolitics"
params.languageAltTitle = "中文"

[taxonomies]
category = "categories"
tag = "tags"