name: Deploy Hugo site to Cloudflare Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy to Cloudflare Pages
        run: |
          npm install -g wrangler@3
          wrangler pages deploy public --project-name=my-blog
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLAREAPITOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLAREACCOUNTID }}